// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {context} from '../models';

export function ActivateLicense(arg1:string):Promise<void>;

export function ActivateOnline(arg1:string):Promise<void>;

export function AddCapital(arg1:number,arg2:number,arg3:string):Promise<void>;

export function BulkImportProducts(arg1:Array<models.Product>):Promise<void>;

export function ChangePassword(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CloseSession(arg1:number,arg2:number,arg3:string):Promise<models.CashierSession>;

export function CreateOrder(arg1:services.OrderRequest):Promise<void>;

export function CreateProduct(arg1:models.Product):Promise<void>;

export function CreateUser(arg1:models.User):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function GetAllSessions():Promise<Array<models.CashierSession>>;

export function GetCashierBalance(arg1:number):Promise<number>;

export function GetCashierTransactions():Promise<Array<models.CashierTransaction>>;

export function GetCategories():Promise<Array<models.Category>>;

export function GetDailyCashSales():Promise<number>;

export function GetDailyPaymentCounts():Promise<Record<string, number>>;

export function GetDailySales():Promise<number>;

export function GetDetailedSales():Promise<Array<Record<string, any>>>;

export function GetLicenseStatus():Promise<services.LicenseStatus>;

export function GetMonthlySales():Promise<number>;

export function GetOpenSession(arg1:number):Promise<models.CashierSession>;

export function GetPaymentCounts(arg1:number,arg2:number):Promise<Record<string, number>>;

export function GetProducts():Promise<Array<models.Product>>;

export function GetSessionSales(arg1:number,arg2:number,arg3:string):Promise<number>;

export function GetSettings():Promise<models.Setting>;

export function GetStockMutations():Promise<Array<models.StockMutation>>;

export function GetUsers():Promise<Array<models.User>>;

export function GetVault():Promise<models.Vault>;

export function GetVaultTransactions():Promise<Array<models.VaultTransaction>>;

export function ImportExcel():Promise<void>;

export function ListPrinters():Promise<Array<string>>;

export function KickDrawer():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<models.User>;

export function OpenSession(arg1:number,arg2:number,arg3:string):Promise<models.CashierSession>;

export function PerformBackup():Promise<void>;

export function PrintReceiptThermal(arg1:services.OrderRequest):Promise<void>;

export function PrintSessionCloseReceipt(arg1:services.SessionClosePrintRequest):Promise<void>;

export function PrintSessionOpenReceipt(arg1:services.SessionOpenPrintRequest):Promise<void>;

export function RecordStockMutation(arg1:models.StockMutation):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestPrint(arg1:string):Promise<void>;

export function UpdateProduct(arg1:models.Product):Promise<void>;

export function UpdateProductStock(arg1:models.Product):Promise<void>;

export function UpdateSettings(arg1:models.Setting):Promise<void>;

export function UpdateUser(arg1:models.User):Promise<void>;
