// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['api']['API']['ActivateLicense'](arg1);
}

export function ActivateOnline(arg1) {
  return window['go']['api']['API']['ActivateOnline'](arg1);
}

export function AddCapital(arg1, arg2, arg3) {
  return window['go']['api']['API']['AddCapital'](arg1, arg2, arg3);
}

export function BulkImportProducts(arg1) {
  return window['go']['api']['API']['BulkImportProducts'](arg1);
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['api']['API']['ChangePassword'](arg1, arg2, arg3);
}

export function CloseSession(arg1, arg2, arg3) {
  return window['go']['api']['API']['CloseSession'](arg1, arg2, arg3);
}

export function CreateOrder(arg1) {
  return window['go']['api']['API']['CreateOrder'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['api']['API']['CreateProduct'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['api']['API']['CreateUser'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['api']['API']['DeleteProduct'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['api']['API']['DeleteUser'](arg1);
}

export function GetAllSessions() {
  return window['go']['api']['API']['GetAllSessions']();
}

export function GetCashierBalance(arg1) {
  return window['go']['api']['API']['GetCashierBalance'](arg1);
}

export function GetCashierTransactions() {
  return window['go']['api']['API']['GetCashierTransactions']();
}

export function GetCategories() {
  return window['go']['api']['API']['GetCategories']();
}

export function GetDailyCashSales() {
  return window['go']['api']['API']['GetDailyCashSales']();
}

export function GetDailyPaymentCounts() {
  return window['go']['api']['API']['GetDailyPaymentCounts']();
}

export function GetDailySales() {
  return window['go']['api']['API']['GetDailySales']();
}

export function GetDetailedSales() {
  return window['go']['api']['API']['GetDetailedSales']();
}

export function GetLicenseStatus() {
  return window['go']['api']['API']['GetLicenseStatus']();
}

export function GetMonthlySales() {
  return window['go']['api']['API']['GetMonthlySales']();
}

export function GetOpenSession(arg1) {
  return window['go']['api']['API']['GetOpenSession'](arg1);
}

export function GetProducts() {
  return window['go']['api']['API']['GetProducts']();
}

export function GetSessionSales(arg1, arg2, arg3) {
  return window['go']['api']['API']['GetSessionSales'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['api']['API']['GetSettings']();
}

export function GetStockMutations() {
  return window['go']['api']['API']['GetStockMutations']();
}

export function GetUsers() {
  return window['go']['api']['API']['GetUsers']();
}

export function GetVault() {
  return window['go']['api']['API']['GetVault']();
}

export function GetVaultTransactions() {
  return window['go']['api']['API']['GetVaultTransactions']();
}

export function ImportExcel() {
  return window['go']['api']['API']['ImportExcel']();
}

export function KickDrawer() {
  return window['go']['api']['API']['KickDrawer']();
}

export function ListPrinters() {
  return window['go']['api']['API']['ListPrinters']();
}

export function Login(arg1, arg2) {
  return window['go']['api']['API']['Login'](arg1, arg2);
}

export function OpenSession(arg1, arg2, arg3) {
  return window['go']['api']['API']['OpenSession'](arg1, arg2, arg3);
}

export function PerformBackup() {
  return window['go']['api']['API']['PerformBackup']();
}

export function PrintReceiptThermal(arg1) {
  return window['go']['api']['API']['PrintReceiptThermal'](arg1);
}

export function PrintSessionCloseReceipt(arg1) {
  return window['go']['api']['API']['PrintSessionCloseReceipt'](arg1);
}

export function PrintSessionOpenReceipt(arg1) {
  return window['go']['api']['API']['PrintSessionOpenReceipt'](arg1);
}

export function RecordStockMutation(arg1) {
  return window['go']['api']['API']['RecordStockMutation'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['API']['Startup'](arg1);
}

export function TestPrint(arg1) {
  return window['go']['api']['API']['TestPrint'](arg1);
}

export function UpdateProduct(arg1) {
  return window['go']['api']['API']['UpdateProduct'](arg1);
}

export function UpdateProductStock(arg1) {
  return window['go']['api']['API']['UpdateProductStock'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['api']['API']['UpdateSettings'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['api']['API']['UpdateUser'](arg1);
}
